from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Callable, Iterable
from urllib.parse import quote

import requests

APIFY_API_BASE = "https://api.apify.com/v2"
DEFAULT_ACTOR_ID = "streamers~youtube-scraper"
TERMINAL_STATUSES = {"SUCCEEDED", "FAILED", "ABORTED", "TIMED-OUT"}


class ApifyError(RuntimeError):
    """Raised when an Apify run cannot be started or collected."""


@dataclass(frozen=True)
class ApifyRun:
    run_id: str
    status: str
    dataset_id: str = ""
    actor_id: str = DEFAULT_ACTOR_ID


def _json_response(response: requests.Response, action: str) -> Any:
    if response.status_code >= 400:
        detail = response.text[:400].strip()
        raise ApifyError(f"A Apify devolveu HTTP {response.status_code} ao {action}: {detail}")
    try:
        return response.json()
    except ValueError as exc:
        raise ApifyError(f"A Apify devolveu uma resposta inválida ao {action}.") from exc


def _headers(token: str) -> dict[str, str]:
    token = str(token or "").strip()
    if not token:
        raise ApifyError("Configure o Apify API Token em Configuração API > API Keys > Serviços e modelos antes de iniciar.")
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


def build_actor_input(
    keywords: Iterable[str],
    *,
    date_filter: str = "week",
    max_results: int = 3,
    max_results_shorts: int = 0,
    length_filter: str = "between420",
    subtitles_language: str = "en",
    download_subtitles: bool = True,
    sorting_order: str = "relevance",
    has_cc: bool = False,
) -> dict[str, Any]:
    values = [str(keyword or "").strip() for keyword in keywords]
    values = [keyword for keyword in values if keyword]
    if not values:
        raise ApifyError("Introduza pelo menos uma palavra-chave para pesquisar no Apify.")
    return {
        "dateFilter": str(date_filter or "week"),
        "downloadSubtitles": bool(download_subtitles),
        "hasCC": bool(has_cc),
        "hasLocation": False,
        "hasSubtitles": False,
        "is360": False,
        "is3D": False,
        "is4K": False,
        "isBought": False,
        "isHD": False,
        "isHDR": False,
        "isLive": False,
        "isVR180": False,
        "lengthFilter": str(length_filter or "between420"),
        "maxResultStreams": 0,
        "maxResults": max(1, min(int(max_results), 100)),
        "maxResultsShorts": max(0, min(int(max_results_shorts), 100)),
        "preferAutoGeneratedSubtitles": False,
        "saveSubsToKVS": False,
        "searchQueries": values,
        "sortingOrder": str(sorting_order or "relevance"),
        "subtitlesLanguage": str(subtitles_language or "en"),
    }


def start_actor_run(token: str, actor_id: str, actor_input: dict[str, Any], *, timeout: int = 60) -> ApifyRun:
    actor_id = str(actor_id or DEFAULT_ACTOR_ID).strip() or DEFAULT_ACTOR_ID
    url = f"{APIFY_API_BASE}/acts/{quote(actor_id, safe='~')}/runs"
    try:
        response = requests.post(url, headers=_headers(token), json=actor_input, timeout=timeout)
    except requests.RequestException as exc:
        raise ApifyError(f"Não foi possível iniciar o actor da Apify: {exc}") from exc
    body = _json_response(response, "iniciar o actor")
    data = body.get("data", body) if isinstance(body, dict) else {}
    run_id = str(data.get("id") or data.get("runId") or "").strip()
    if not run_id:
        raise ApifyError("A Apify iniciou o pedido, mas não devolveu um run ID.")
    status = str(data.get("status") or "RUNNING").upper()
    dataset_id = str(data.get("defaultDatasetId") or data.get("datasetId") or "").strip()
    return ApifyRun(run_id=run_id, status=status, dataset_id=dataset_id, actor_id=actor_id)


def get_actor_run(token: str, run_id: str, *, timeout: int = 30) -> ApifyRun:
    run_id = str(run_id or "").strip()
    if not run_id:
        raise ApifyError("A execução Apify não tem run ID.")
    url = f"{APIFY_API_BASE}/actor-runs/{quote(run_id, safe='')}"
    try:
        response = requests.get(url, headers=_headers(token), timeout=timeout)
    except requests.RequestException as exc:
        raise ApifyError(f"Não foi possível consultar o estado da execução Apify: {exc}") from exc
    body = _json_response(response, "consultar o estado da execução")
    data = body.get("data", body) if isinstance(body, dict) else {}
    status = str(data.get("status") or "UNKNOWN").upper()
    dataset_id = str(data.get("defaultDatasetId") or data.get("datasetId") or "").strip()
    actor_id = str(data.get("actId") or data.get("actorId") or DEFAULT_ACTOR_ID)
    return ApifyRun(run_id=run_id, status=status, dataset_id=dataset_id, actor_id=actor_id)


def get_dataset_items(token: str, dataset_id: str, *, limit: int = 100, timeout: int = 60) -> list[dict[str, Any]]:
    dataset_id = str(dataset_id or "").strip()
    if not dataset_id:
        raise ApifyError("A execução Apify terminou sem devolver um dataset ID.")
    url = f"{APIFY_API_BASE}/datasets/{quote(dataset_id, safe='')}/items"
    try:
        response = requests.get(
            url,
            headers=_headers(token),
            params={"format": "json", "clean": "true", "limit": max(1, min(int(limit), 1000))},
            timeout=timeout,
        )
    except requests.RequestException as exc:
        raise ApifyError(f"Não foi possível carregar o dataset Apify: {exc}") from exc
    body = _json_response(response, "carregar o dataset")
    if not isinstance(body, list):
        raise ApifyError("O dataset Apify não devolveu uma lista de vídeos.")
    return [item for item in body if isinstance(item, dict)]


def abort_actor_run(token: str, run_id: str, *, timeout: int = 30) -> None:
    url = f"{APIFY_API_BASE}/actor-runs/{quote(str(run_id), safe='')}/abort"
    try:
        response = requests.post(url, headers=_headers(token), params={"gracefully": "0"}, timeout=timeout)
    except requests.RequestException as exc:
        raise ApifyError(f"Não foi possível cancelar a execução Apify: {exc}") from exc
    _json_response(response, "cancelar a execução")


def wait_for_actor_run(
    token: str,
    run: ApifyRun,
    *,
    poll_interval: int = 10,
    timeout_seconds: int = 900,
    on_status: Callable[[ApifyRun], None] | None = None,
) -> ApifyRun:
    import time

    started = time.monotonic()
    current = run
    while current.status not in TERMINAL_STATUSES:
        if time.monotonic() - started >= max(10, int(timeout_seconds)):
            raise ApifyError(f"A execução Apify excedeu o limite de {int(timeout_seconds)} segundos.")
        if on_status:
            on_status(current)
        time.sleep(max(1, int(poll_interval)))
        current = get_actor_run(token, run.run_id)
    if on_status:
        on_status(current)
    if current.status != "SUCCEEDED":
        raise ApifyError(f"A execução Apify terminou com o estado {current.status}.")
    return current


def _first_value(item: dict[str, Any], *keys: str, default: Any = "") -> Any:
    for key in keys:
        value = item.get(key)
        if value not in (None, ""):
            return value
    return default


def _number(value: Any) -> int | float:
    if isinstance(value, bool):
        return 0
    if isinstance(value, (int, float)):
        return value
    text = str(value or "").replace(",", "").strip()
    try:
        number = float(text)
    except ValueError:
        return 0
    return int(number) if number.is_integer() else number


def clean_srt(value: Any) -> str:
    if isinstance(value, dict):
        value = value.get("srt") or value.get("text") or value.get("content") or ""
    if isinstance(value, list):
        parts = [clean_srt(part) for part in value]
        return " ".join(part for part in parts if part).strip()
    text = str(value or "")
    if not text.strip():
        return ""
    text = re.sub(r"^\s*\d+\s*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"^\s*\d{2}:\d{2}:\d{1,2},\d{1,3}\s*-->\s*\d{2}:\d{2}:\d{1,2},\d{1,3}.*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n{2,}", "\n", text)
    return re.sub(r"\s+", " ", text.replace("\n", " ")).strip()


def extract_transcript(item: dict[str, Any]) -> str:
    subtitles = item.get("subtitles")
    if isinstance(subtitles, list):
        for subtitle in subtitles:
            text = clean_srt(subtitle)
            if text:
                return text
    for key in ("srt", "transcript", "subtitlesText", "captionText"):
        text = clean_srt(item.get(key))
        if text:
            return text
    return ""


def vsc_ratio(view_count: Any, subscriber_count: Any, comments_count: Any) -> float:
    views = float(_number(view_count) or 0)
    subscribers = float(_number(subscriber_count) or 0)
    comments = float(_number(comments_count) or 0)
    subscriber_component = (views / subscribers) * 0.7 if subscribers else 0.0
    comment_component = (comments / views) * 0.3 if views else 0.0
    return round(subscriber_component + comment_component, 6)


def normalize_video_item(item: dict[str, Any]) -> dict[str, Any]:
    views = _first_value(item, "viewCount", "views", default=0)
    subscribers = _first_value(item, "numberOfSubscribers", "subscriberCount", "subscribers", default=0)
    comments = _first_value(item, "commentsCount", "commentCount", "comments", default=0)
    transcript = extract_transcript(item)
    return {
        "video_id": str(_first_value(item, "id", "videoId", default="")),
        "url": str(_first_value(item, "url", "videoUrl", default="")),
        "title": str(_first_value(item, "title", default="Sem título")),
        "channel_name": str(_first_value(item, "channelName", "channelTitle", default="Sem canal")),
        "channel_url": str(_first_value(item, "channelUrl", default="")),
        "thumbnail_url": str(_first_value(item, "thumbnailUrl", "thumbnail", default="")),
        "duration": str(_first_value(item, "duration", "durationText", default="")),
        "publish_date": str(_first_value(item, "date", "publishedAt", "uploadDate", default="")),
        "view_count": _number(views),
        "subscriber_count": _number(subscribers),
        "comments_count": _number(comments),
        "vsc_ratio": vsc_ratio(views, subscribers, comments),
        "transcript": transcript,
        "transcript_status": "disponível" if transcript else "sem transcrição",
        "summary": "",
        "summary_status": "pendente" if transcript else "não aplicável",
    }


def normalize_video_items(items: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    return [normalize_video_item(item) for item in items]
