name: Remove npm version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to remove"
        required: true
        type: string

permissions:
  contents: read

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Remove npm version
        run: npm unpublish "@danhachuel/thunderbolt@${{ inputs.version }}" --force --registry=https://registry.npmjs.org/ --loglevel=http
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
