[theme]
base = "dark"
primaryColor = "#35A7FF"
backgroundColor = "#0B1118"
secondaryBackgroundColor = "#121B26"
textColor = "#F4F8FB"
font = "sans serif"

[client]
toolbarMode = "auto"

[logger]
hideWarningOnDirectExecution = true
